### ISSUE TITLE
First image/Cover missing

### ISSUE THREAD

**Issue by darodi** [celogeek/go-comic-converter#1]
Salut @celogeek , 

Beau boulot!

J'aime le fait que je peux builder une version pour armv7 sans devoir mettre en place toute une usine à gaz ou sans devoir utiliser des dockers.

Je pense avoir trouvé un bug. Il manque la première image. cf. ci-dessous.

![image](https://user-images.githubusercontent.com/4682830/222601086-8f122f5f-6657-48c4-b444-4e5324d3a2d0.png)

Autre point, sans upscaling, le "panel view" ne zoome pas vraiment dans certains cas, mais c'est juste un nice-to-have.

**Comment by celogeek** [comment]
Pour la premiere page, en fait je la concidére comme le cover. Du coup je ne la remet pas a nouveau dans la page 1.
Ce qu'il se passe, c'est lorsque j'ouvre le comic, je met une page avec le titre et le nombre de partie.
Genre: One Piece 123 - Part 1/2
Si on fait aller cover, on voit la page 1.

Pour ce qui est du panel view, bien vue. Lorsque les images sont plus petite que la resolution du device, je garde leur taille sans les agrandir. Ensuite normalement le device va les upscale lui meme.
Je vais essayer de voir ce qu'il se passe pour le panel view dans ce cas la.

**Comment by celogeek** [comment]
Small Image: Panel View fixed ;)

J'ai agrandi les petites images (plus petites que la resolution du device), et les panel view fonctionne.

J'vais ajouter une option pour le desactiver. Effectivement sur Kindle Scribe c'est vraiment pas necessaire, et j'ai deja eut du mal a en sortir.

**Comment by darodi** [comment]
> Small Image: Panel View fixed ;)

Merci! 👍 

> Pour la premiere page, en fait je la considère comme le cover. Du coup je ne la remet pas a nouveau dans la page 1. Ce qu'il se passe, c'est lorsque j'ouvre le comic, je met une page avec le titre et le nombre de partie. Genre: One Piece 123 - Part 1/2 Si on fait aller cover, on voit la page 1.

OK, je comprends mieux.
Je suis habitué à prendre les mangas sur le site officiel de la [shueisha ](https://mangaplus.shueisha.co.jp/manga_list/hot)
Ils ont un chapitre par semaine, mais il n'y a pas de cover habituellement.
La kindle paper white 5 affiche la page 1 par défaut en passant la cover.
Ca doit être pour ça que la plupart des autres convertisseurs créent une cover et recopient la cover en page 1.

**Comment by celogeek** [comment]
Effectivement. Je vais faire une option pour ca.
Par exemple:
```
--no-cover: indicate if your comics doesn't have a cover
```

Je pourrais utiliser la premier page pour faire la cover, et aussi l'inclure.
Et par default, j'inclus pas la cover pour eviter une repetition au debut.

J'vais ajouter une option pour ne pas inclure le panel view aussi
```
--no-panel: do not include panel view (zooming option)
```

**Comment by celogeek** [comment]
J'ai ajouté le --nocover.

Il support le cas ou le cover est plus large que long, avec l'autosplit.

Du coup avec cette option, la premiere image est utilisé comme cover et aussi incluse comme une image apres le titre.

**Comment by celogeek** [comment]
Quand j'enlève le panel view, j'ai pleins d'options en plus sur le document, dont le panel view en option !
Avec Panel View intégré:
- Animation non disponible
- Ajuster à l'écran non disponible
- Panneau Virtuel n'apparait pas

Sans les options de panel view dans l'epub:
- Animation disponible
- Ajuster à l'écran disponible (mais conserve pas l'aspect ratio)
- Panneau Virtuel disponible

Je me demande si c'est encore utile de mettre cette option.
Peut etre que je devrais le desactiver par defaut et mettre une option pour l'ajouter au besoin.

**Comment by celogeek** [comment]
J'ai mis une option "-addpanelview", qui est désactivé par default.
Ca debloque plein de possibilité dont le panel view géré par kindle !

Lorsque j'envoie le fichier sur sendtokindle, amazon me renvoie un mail:

```
Dear Kindle Customer,

We are reaching out to let you know that the following document(s), sent to your Kindle library at 10:39 PM on Sat, Mar 04, 2023 GMT, contains incompatible elements for Kindle format conversion. We’ve still delivered your document so you can read it on Kindle, but it won’t support writing features with Kindle Scribe (e.g., sticky notes or on-page writing):
* nocover.epub


To enable writing features with Kindle Scribe, here are some helpful tips about things you can do to make your document(s) compatible before sending it:

Split large tables into several smaller tables, align the direction of text in the tables, and remove drop-caps in the tables.

Remove multi-media content such as audio, video, and SVG images.

Remove mathematical equations.

Remove images that contain linear gradients.

Remove password protection or any other security settings.

Make sure your document doesn’t contain footnotes inside footnotes.

Make sure your document can be opened on a computer.

Make sure your document doesn’t have more than 8,000 pages.

Try sending the document again via [Send-to-Kindle](https://www.amazon.com/gp/f.html?C=3F77JOWY15270&K=L8X4OFHDLFLL&M=urn:rtn:msg:20230304224022181a936b3d134180bb3870118490p0na&R=3L7JVXED4BSMM&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fsendtokindle%3Fref_%3Dpe_1825130_692203110&H=NRNK6LD47YO6BSTT64TYV8H3RJIA&ref_=pe_1825130_692203110).


To learn more about converting personal documents to a Kindle format, please visit our [help page]


Regards, 
Amazon Kindle Support
```

Tu as la meme chose de ton coté ?
Je vais essayer de trouver ce qui cloche. C'est pas tres explicit.

**Comment by darodi** [comment]
> Sans les options de panel view dans l'epub:
> 
>     * Animation disponible
> 
>     * Ajuster à l'écran disponible (mais conserve pas l'aspect ratio)
> 
>     * Panneau Virtuel disponible
> 
> 

Je ne me rappelle pas avoir déjà vu ces options sur une PW5. Je vais tester.
Pour le mail, je vais voir également, mais je n'ai pas de scribe.

**Comment by darodi** [comment]
Je confirme, je n'ai pas ces options sur une KPW5.
Pas de mail en utilisant sendtokindle avec une KPW5 non plus.

Encore merci pour les changements, c'est OK pour moi, je ferme l'issue.
