### ISSUE TITLE
Option to skip corrupted files

### ISSUE THREAD

**Issue by rogatty** [celogeek/go-comic-converter#16]
As mentioned in https://github.com/celogeek/go-comic-converter/issues/5#issuecomment-1500219879, it would be great to have an option to skip corrupted files. I had to unpack the comic, delete file manually, pack it again, get an error on the next file, unpack, delete, pack and run the tool again. An option to skip these files would be much better. 🙂

Would be perfect to auto-fix the files if possible, but I found it's not that easy with golang image package: https://github.com/golang/go/issues/10447#issuecomment-1505832127

**Comment by celogeek** [comment]
Hi,
First of all, the tools can process a directory, so you can unpack, run the directory, and each time an image is corrupted, fix it and retry. You don't need to repack the directory each time.

I see someone do a fix for some errors, so that can help parsing a corrupted images instead of failing entirely.

What I can do is:
- use a better alternative image processing
- add an option to skip corrupted images and record then in a files

For example:
- input: comics.cbz
- output: comics.epub
- error log if any: comics.errors.txt

it will list in this all files that failed to parse.

Can you create a file I can download with some corrupted example (and sain one), so I can play with it ?

**Comment by celogeek** [comment]
I've create a branch to try "libjpeg-turbo".

https://github.com/celogeek/go-comic-converter/tree/turbo

You need to install jpeg-turbo,
on mac:
```
brew install jpeg-turbo
```

Then run
```
go run -tags turbo . --YOUROPTIONS
```

Tell me if it works better with your corrupted files.

**Comment by rogatty** [comment]
Wow, you're quick! 🙂 I can take a longer look at evening. If you want a file to test, https://archive.org/download/battle-angel-alita-1/Battle%20Angel%20Alita%206.cbr is the archive I had problems with.
```
go-comic-converter -input Battle\ Angel\ Alita\ 6.cbr
Go Comic Converter

Options:
    Input                     : Battle Angel Alita 6.cbr
    Output                    : Battle Angel Alita 6.epub
    Author                    : GO Comic Converter
    Title                     : Battle Angel Alita 6
    Workers                   : 8
    Profile                   : KV - Kindle Paperwhite 3/4/Voyage/Oasis - 1072x1448
    Format                    : jpeg
    Quality                   : 90
    Grayscale                 : true
    Grayscale Mode            : normal
    Crop                      : true
    CropRatio                 : 1 Left - 1 Up - 1 Right - 3 Bottom
    AutoContrast              : false
    AutoRotate                : false
    AutoSplitDoublePage       : true
    NoBlankImage              : true
    Manga                     : false
    HasCover                  : true
    LimitMb                   : 200 Mb
    StripFirstDirectoryFromToc: false
    SortPathMode              : path=alphanum, file=alpha
    Foreground Color          : #000
    Background Color          : #FFF
    Resize                    : true
    Aspect Ratio              : auto
    Portrait Only             : false
    Title Page                : always

[1/2] Processing        4% [=>                                                          ] (10/213) [0s:3s]
error processing image Page023.jpg: invalid JPEG format: bad Huffman code
```

**Comment by celogeek** [comment]
I've try you file and it seems to go through with a warning from the C library:
```
go run -tags turbo . -input Battle\ Angel\ Alita\ 6.cbr
Go Comic Converter

Options:
    Input                     : Battle Angel Alita 6.cbr
    Output                    : Battle Angel Alita 6.epub
    Author                    : GO Comic Converter
    Title                     : Battle Angel Alita 6
    Workers                   : 20
    Profile                   : SR - Standard Resolution - 1200x1920
    Format                    : jpeg
    Quality                   : 90
    Grayscale                 : true
    Grayscale Mode            : normal
    Crop                      : true
    CropRatio                 : 1 Left - 1 Up - 1 Right - 3 Bottom
    AutoContrast              : false
    AutoRotate                : false
    AutoSplitDoublePage       : false
    NoBlankImage              : true
    Manga                     : true
    HasCover                  : true
    StripFirstDirectoryFromToc: false
    SortPathMode              : path=alphanum, file=alpha
    Foreground Color          : #000
    Background Color          : #FFF
    Resize                    : true
    Aspect Ratio              : 1:1.60
    Portrait Only             : false
    Title Page                : always

[1/2] Processing        0% [                                                            ] (2/213) [0s:8s]Corrupt JPEG data: bad Huffman code
[1/2] Processing      100% [============================================================] (213/213)
[2/2] Writing Part    100% [============================================================] (1/1)

Completed in 2.213s, Memory usage 515 Mb
```

And the image looks like:

![img_23_p0](https://github.com/celogeek/go-comic-converter/assets/65178/9162b8e0-cd42-4da0-8641-66526595ed4f)

**Comment by celogeek** [comment]
Just in case you want to test the branch:

```
git clone https://github.com/celogeek/go-comic-converter
git checkout turbo
go run -tags turbo . --input Battle\ Angel\ Alita\ 6.cbr
```

If I release, you should be able to install with:

```
go install -tags turbo github.com/celogeek/go-comic-converter/v2@TAGS
```

Also I will try to see how to detect the error and create the file to log it and keep going.

**Comment by rogatty** [comment]
I confirm it works as expected - adds the corrupted image to epub which seems a sensible fallback to me. 👍 

I agree it would be nice to have a list of bad images to check how they look. I'm personally fine with the list being in the output instead of a dedicated file, but I don't know all the flows you want to support.

Thank you for the quick fix!

**Comment by celogeek** [comment]
I've test the jpeg-turbo lib alone with the corrupted file.
I can't find any option that let me know it's corrupted or something goes wrong with it, and even worse, it output on stderr a message I cannot easily capture.

The normal flow is to return may be the partial image with an error, and then you can deal with it.

I will report that issue, and try other solution.

I may end up with using the normal lib (or may be I can try the patched one), so at least I know I've got an issue, I can save it in a text file and do a proper report of issue.
Then I can stop or keep going with an option, and may be replace the bad image with a static image with a text like "img_XXX is corrupted" or something.

I will keep looking.

Also jpeg-turbo is a bit faster, but it's supposed to be 5x faster than the standard lib, which is not the case as far as I can see.
I save like 1 or 2 sec on 20
Even if I use it to encode, and it doesn't support all format in output, for example the special one I use for thumbnail.

So not so fast, not good at telling you there is an error, and do not support all input images ...

I will test other lib (C lib and alternative patched standard lib).

Keep this open please.

**Comment by celogeek** [comment]
I've finish the detection of corrupted images.
For now I use the standard library, so the image is rejected but I replace it by a text indicated the image is corrupted and report all corrupted images at the end

https://github.com/celogeek/go-comic-converter/releases/tag/v2.6.4
