### ISSUE TITLE
Better spread splitting

### ISSUE THREAD

**Issue by manueldidonna** [celogeek/go-comic-converter#19]
Hello @celogeek 

I prefer this project over kcc but the latter handle spread splitting better. It would be great if there was an option to split a page into two pages and remove the original page from the output.

Currently, if I enable the splitting the converted epub will contains both the original image and the two new pages

**Comment by celogeek** [comment]
Hi,
The double page work in a way you have the overview then a zoom in.
On Landscape the double page show full screen so it's even better.

I will add an option to not keep the double page if splitted.

**Comment by manueldidonna** [comment]
> Hi,
> 
> The double page work in a way you have the overview then a zoom in.
> 
> On Landscape the double page show full screen so it's even better.
> 
> 
> 
> I will add an option to not keep the double page if splitted.

Thank you!

**Comment by yoanhg421** [comment]
I second that.

**Comment by celogeek** [comment]
I add an option to keep or not double page if splitted:

```
go install github.com/celogeek/go-comic-converter/v2@v2.6.6
```

Then you can switch it off (on by default)
```
go-comic-converter -save -autosplitdoublepage -keepdoublepageifsplitted=false
```

I ensure it will spread properly in landscape mode, the same way when we keep the double page.

**Comment by yoanhg421** [comment]
Awesome.  Can’t wait to give it a try.  👍
