### ISSUE TITLE
Author of epub not being set

### ISSUE THREAD

**Issue by stavguo** [celogeek/go-comic-converter#2]
Awesome project! I was wondering if you could help me figure out why the author metadata is not being set.

This is the command I'm using on a directory of images (/tmp):
`go-comic-converter --profile KPW5 --manga --autosplitdoublepage --nocrop --noblankpage --title "Dandadan: Chapter 1" --author "TATSU Yukinobu" --input tmp`

The terminal output:
`Go Comic Converter

Options:
    Input              : ../tmp
    Output             : ../tmp.epub
    Profile            : KPW5 - Kindle Paperwhite 5/Signature Edition - 1236x1648 - 16 levels of gray
    Author             : TATSU Yukinobu
    Title              : Dandadan: Chapter 1
    Quality            : 85
    Crop               : false
    Brightness         : 0
    Contrast           : 0
    AutoRotate         : false
    AutoSplitDoublePage: true
    NoBlankPage        : true
    Manga              : true
    HasCover           : true
    AddPanelView       : false
    LimitMb            : nolimit
    Workers            : 8

[1/2] Processing      100% [============================================================] (67/67)        
[2/2] Writing Part    100% [============================================================] (1/1)`

But on Calibre and apple Books, the author is "GO Comic Converter". If there's any other info you would like me to provide, please let me know!

**Comment by celogeek** [comment]
I fix it in v1.1.8. Thanks for letting me know.
I also fix publisher/published tag.

let me know if it's ok now.

**Comment by stavguo** [comment]
Using the same command/set up as before, the author metadata is being set now through Calibre. However, some other things have changed:

1. EPUBs are no longer opening through Apple Books.
2. After using Send to Kindle web, the author went from "GO Comic Converter" to "Unknown" on my Kindle.
3. On my Kindle, the quality seems to have decreased. It also no longer fills the full screen like a .MOBI. It shows the location and page at the bottom of the screen like when I read .AZW3. Before on v1.1.7, the quality at 100 was phenomenal and filled the entirety of my Kindle PW5 screen.

Additionally, how do you set the publisher? I don't think the flag is present in the usage instructions. Nonetheless, thank you for responding and the great work!

**Comment by darodi** [comment]
> This is the command I'm using on a directory of images (/tmp):
> `go-comic-converter --profile KPW5 --manga --autosplitdoublepage --nocrop --noblankpage --title "Dandadan: Chapter 1" --author "TATSU Yukinobu" --input tmp`

Are you using one or two "-" for your options?

**Comment by stavguo** [comment]
@darodi I was using two hyphens because of the [usage](https://github.com/celogeek/go-comic-converter#usage) example.  I have tried using one hyphen and two hyphens (with v.1.1.7 and v.1.1.8) and it made no difference.

I compared v.1.1.7 and v.1.1.8 on the same folder of images. This was the command I used: `go-comic-converter -profile KPW5 -manga -autosplitdoublepage -nocover -nocrop -noblankpage -quality 100 -limitmb 200 -title "Grand Blue: Chapter 8.5" -author "INOUE Kenji" -input tmp`

Comparing the two, they both created ePubs of the same size (20.6 mb). Using [send to kindle](https://www.amazon.com/sendtokindle) to send the ePub to my kindle to read, the one created by v.1.1.7 was compressed down to 8.8mb. The image is crisp and fits my screen perfectly. The version created by v.1.1.8 was compressed down to 2.4 mb once it was sent to my Kindle, and the image lost a considerable amount of quality. It also has the added information at the bottom (location and percentage) that wasn't there before. I did not change any settings, I just opened one after the other.

**Comment by celogeek** [comment]
Oh. may be kindle interpret the epub with some additional information differently. I will run test locally and fix that.

**Comment by celogeek** [comment]
Ok found it. the epub is not valid. I go too fast in my release, I miss some checks.
Please try again the last version.

**Comment by stavguo** [comment]
@celogeek it works great now! Thanks!

**Comment by celogeek** [comment]
I close this issue. Thanks.
