### ISSUE TITLE
Pipe mode to communicate with external tools

### ISSUE THREAD

**Issue by celogeek** [celogeek/go-comic-converter#22]
That would be great. I was reading the stderr but it was making everything to slowdown because I had to regex the output every time to get the progress, but removed it and just have a spinner out. 

Having a better way to communicate with your binary would be awesome. specially JSON and stdout.
I need to read the progress (percent) as integer 20 || 90  and the time elapsed and remaining. 

I already get the used settings and set the -quiet flag.

I'll implement the progress bar in the frontend, otherwise I have to extract the information.

I'm building your binary from source, I'm not sure if you have plans to release the cross platform binaries in the release page, but right now it have to pull the changes, build, and then update my app. 

The plan is to use Github Actions so that I can also release CrossPlatform builds. 

Let me know if you want to give the app a try. 
Right now it only works on M1 Macs.

_Originally posted by @yoanhg421 in https://github.com/celogeek/go-comic-converter/issues/21#issuecomment-1732631789_

**Comment by celogeek** [comment]
For building binary, the go install do it on the platform. no need to download the source manually.

```
GOPATH=$PWD/go go install github.com/celogeek/go-comic-converter/v2@v2.6.7
```
The binary is in $PWD/go/bin/go-comic-converter

I can automate building for some platform, but it may be hard to get it on mac, I need to check if I can crossbuild it for mac from github action.

**Comment by celogeek** [comment]
I've start this branch:
https://github.com/celogeek/go-comic-converter/tree/json-pipe

**Comment by yoanhg421** [comment]
Awesome.  I think you can build cross platform.  
Setting it up it’s what’s going to be tricky.  If you do figure it out.  If you can add the -$TARGET_TRIPLE to the output filenames that would be awesome.  
like this `go-comic-converter-x86_64-win32.exe`
That would really help.

**Comment by yoanhg421** [comment]
Not sure if you have seen this project [mapaki](https://github.com/tsopeh/mapaki)
It implemented the mobi library in Go. And it;s really fast processing images, but it doesn't implement the file limit so it's really slow when it comes to really large Mangas like the One Piece 7.7GB. 
The process dies and never finishes.

**Comment by celogeek** [comment]
Indeed I've seen the library he used and exchange with the Author.
I'm gonna do it at some point, it will take me a bit of time.

Basically the 2nd step will be writing the AZW3 instead of the ePub.

The main reason I want to implement that other using the cloud service is the ability to create higher resolution images on large device like Kindle Scribe.
I don't understand why Amazon limit the size to 1920x1200 despite the Kindle scribe has a resolution of 2480x1860.

Some people have try the tools here and have a much sharper result.

The disadvantage is that it's not possible to have the file on the cloud, and you need to handle the thumbnail yourself.
Also I will create Personal Document instead of Book, to be able to distinguish file I buy vs file I create myself.
Also UUID of the generated document is randomise, so a link to the book will always failed otherwise.

Also the file generated doesn't have the latest feature supported by Amazon. It's mostly reverse engineering here and the file works but looks outdated.


I will first make a pipe / json version of the output.
Then add a build for all platform.
And finally working on awz3 output.

**Comment by yoanhg421** [comment]
If you use calibre to manage your library you don’t have to worry about the thumbnail as it does it for you.  

The uuid doesn’t have to be randomized, just have to be unique otherwise you end up multiple books with the same cover.  I was trying out mapaki and noticed the bug.  You just need to create a uint32 hash from the book title or other constant from the book, and you should always get the same ID for the same book.   

Amazon keeping their conversion tools closed source makes it really hard to work with those format and their devices are some of the cheapest and best e-readers out there but they don’t support EPUBs.

I have a Scribe too and I don’t use it as much because the images do look a little blurry.  Usually go back to my Kindle PW looks much sharper there.

**Comment by celogeek** [comment]
About UUID, I always generate a random id. It allow me to change the Go Converter settings and reup the same book.
Otherwise it may have issue with duplicates here. Same book, same author, diff settings.
I may be use all of that to have consistant ID, but it's way easier to randomize it, and probably safer.

**Comment by yoanhg421** [comment]
I see.  👍

**Comment by celogeek** [comment]
I've release the json output mode.
it will send to stdout json instead of formatted text

Here an example:
```{"data":{"applebookcompatibility":false,"aspectratio":1.6,"author":"GO Comic Converter","autocontrast":false,"autorotate":false,"autosplitdoublepage":false,"backgroundcolor":"FFF","crop":true,"crop_ratio":{"bottom":3,"left":1,"right":1,"up":1},"foregroundcolor":"000","format":"jpeg","grayscale":true,"grayscale_mode":0,"hascover":true,"input":"~/Downloads/test","limitmb":200,"manga":true,"noblankimage":true,"output":"~/Downloads/test.epub","portraitonly":false,"profile":{"code":"SR","description":"Standard Resolution","width":1200,"height":1920},"quality":90,"resize":true,"sortpathmode":1,"stripfirstdirectoryfromtoc":false,"title":"x","titlepage":1,"workers":8},"type":"options"}
{"data":{"description":"Processing","progress":{"current":1,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Processing","progress":{"current":2,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Processing","progress":{"current":3,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Processing","progress":{"current":4,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Processing","progress":{"current":5,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Processing","progress":{"current":6,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Processing","progress":{"current":7,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Processing","progress":{"current":8,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Processing","progress":{"current":9,"total":9},"steps":{"current":1,"total":2}},"type":"progress"}
{"data":{"description":"Writing Part","progress":{"current":1,"total":1},"steps":{"current":2,"total":2}},"type":"progress"}
{"data":{"elapse_ms":936,"memory_usage_mb":860},"type":"stats"}
```

**Comment by yoanhg421** [comment]
Awesome, thank you, I'll give it a try.

**Comment by yoanhg421** [comment]
This works perfect. Thank you.
