### ISSUE TITLE
Epub problems on Koko device

### ISSUE THREAD

**Issue by yoanhg421** [celogeek/go-comic-converter#23]
Hi.
I finally got my hands on a Koko Libra 2 and the screen is gorgeous. 

I'm having issues with the epubs that are coming out. 
I chose the Kobo H2O profile and settings are the same I use for making MOBI. 

1.  The images don't take up the full screen, 
2. Images seem affected by the margins in the font settings. They move left and right depending on the margin size selected. (not centered like in Kindle. looks more like the Calibre Book Viewer)
4. There is a blank page between every page. 
5. TOC is broken. only shows the name of the Manga. not the chapter list. 

I tested making an epub with KCC and none of these issues are present. Books look just like go-comic-converter do in Kindle.  

I know you don't have a Kobo device so this might be hard to figure out.

What do you think?

**Comment by celogeek** [comment]
I wonder if the style "right" works on this device.
Did you test the portrait-only ?

**Comment by celogeek** [comment]
I think I will improve profile and add a device type like : apple, kobo, kindle.
And based on that the ePub will use different generation.

I really doubt I can create 1 ePub that works the same every where, or the render won't be the best for each of them.

**Comment by yoanhg421** [comment]
> I wonder if the style "right" works on this device. Did you test the portrait-only ?

I tried portrait only.  And landscape.  It always looks the same.  Looks like Kobo uses the first image as cover so hascover has to be disabled. 

One things I noticed the most is that make I make a an epub  it gets treated like text.  Margins and justify affect it.  But with KCC image shows center regardless of what text settings you have on text

about the render.  Yes. It won’t be the best. KCC works on portraits and Apple Books landscape. But double pages get split and sometimes show up in the wrong locations.

**Comment by celogeek** [comment]
About Kobo, I don't have the device. So is they any possibilities for me to see how it render on this device? an emulator or simulator ?

**Comment by yoanhg421** [comment]
unfortunately there is not an emulator or app that renders exactly.
but i can show you the differences in the Calibre viewer. 

```
[Log] Go Comic Converter (Main.vue, line 126)

Options:
    Input                     : /Users/yoanherrera/Downloads/Comics/Manga/Kill la Kill
    Output                    : /Users/yoanherrera/Downloads/Comics/ToProcess/Output/Kill la Kill.epub
    Author                    : Comic Converter
    Title                     : Kill la Kill
    Workers                   : 10
    Profile                       : KoL - Kobo Libra H2O/Kobo Libra 2 - 1264x1680
    Format                        : jpeg
    Quality                       : 80
    Grayscale                     : false
    Crop                          : true
    CropRatio                     : 1 Left - 1 Up - 1 Right - 3 Bottom
    AutoContrast                  : false
    AutoRotate                    : false
    AutoSplitDoublePage           : true
    KeepDoublePageIfSplitted      : true
    NoBlankImage                  : true
    Manga                         : true
    HasCover                      : false
    StripFirstDirectoryFromToc    : true
    SortPathMode                  : path=alphanum, file=alpha
    Foreground Color              : #000
    Background Color              : #FFF
    Resize                        : true
    Aspect Ratio                  : 1:1.60
    Portrait Only                 : true
    Title Page                    : never


Completed in 10.346s, Memory usage 621 Mb
```

KCC on the left. go-comic-converter on the right. 
Here you can see the image is wide, but has a weird margin on top that is usually there with text books. Makes the image be lower than it should. 

<img width="1728" alt="Screenshot 2023-09-30 at 9 37 22 AM" src="https://github.com/celogeek/go-comic-converter/assets/26210577/3c8098a9-b2c9-4273-a9aa-991b5b3a7325">

with the book window stretched wider.
<img width="1728" alt="Screenshot 2023-09-30 at 9 38 05 AM" src="https://github.com/celogeek/go-comic-converter/assets/26210577/4106f86c-1a0b-47e8-a39d-d7675eec855e">

<img width="1728" alt="Screenshot 2023-09-30 at 9 40 16 AM" src="https://github.com/celogeek/go-comic-converter/assets/26210577/fde60f45-1313-4ccc-b544-da86b2debe8b">

Folder Structure. 

KCC has a nav file and toc is different format. 

<img width="1728" alt="Screenshot 2023-09-30 at 9 50 49 AM" src="https://github.com/celogeek/go-comic-converter/assets/26210577/25193ef5-5fd5-4a30-bd66-6e55aeffff86">

 xhtml styles is different. 

<img width="1728" alt="Screenshot 2023-09-30 at 9 49 25 AM" src="https://github.com/celogeek/go-comic-converter/assets/26210577/8007595c-99a4-49ae-89e8-c7659c3429de">

content.opf has small differences. 

<img width="1728" alt="Screenshot 2023-09-30 at 9 50 38 AM" src="https://github.com/celogeek/go-comic-converter/assets/26210577/744d2344-38ed-4e9b-ad20-4ccc39274fe9">


KCC styles 
```
@page {
margin: 0;
}
body {
display: block;
margin: 0;
padding: 0;
}
```

go-comic-converter styles 
```
body {
    color: #000;
    background: #FFF;
    top: 0;
    left: 0;
    margin: 0;
    padding: 0;
    width: 1050px;
    height: 1680px;
    text-align: center;
}
img {
  position: absolute;
  margin:0;
  padding:0;
  z-index:0;
}
```

I hope this helps somehow. 
I'm also available to test on the device and can send you screen shots.

**Comment by yoanhg421** [comment]
Go-Comic-Converter on Kobo

You can see the render and how the page moves when the text margin settings change. 

![IMG_5049](https://github.com/celogeek/go-comic-converter/assets/26210577/98740358-12c7-4d0f-bdd9-f921d9b156fa)
![IMG_5050](https://github.com/celogeek/go-comic-converter/assets/26210577/0b9e52d2-7983-46e1-adff-66a3b80598ba)
![IMG_5051](https://github.com/celogeek/go-comic-converter/assets/26210577/4bf56ad3-4a35-4f36-a613-d157b4ce08ae)
![IMG_5052](https://github.com/celogeek/go-comic-converter/assets/26210577/583a87a1-3b89-47a2-aafc-0900719ed31b)
![IMG_5053](https://github.com/celogeek/go-comic-converter/assets/26210577/7e8c9428-1966-4ae2-a6fc-a42faf207446)
![IMG_5054](https://github.com/celogeek/go-comic-converter/assets/26210577/396b03f1-9c82-4559-99dc-a60eed76db15)
![IMG_5055](https://github.com/celogeek/go-comic-converter/assets/26210577/3b9fe456-715f-47c9-8445-0778be4d3407)

**Comment by yoanhg421** [comment]
KCC Image is unaffected by changes to text settigns. 
![IMG_5056](https://github.com/celogeek/go-comic-converter/assets/26210577/d98509df-80d2-44b0-af08-cc1a69baf292)
![IMG_5057](https://github.com/celogeek/go-comic-converter/assets/26210577/0e881382-6c8e-4a9e-b1a6-dce944629c8e)
![IMG_5058](https://github.com/celogeek/go-comic-converter/assets/26210577/d47e99d6-3266-49df-ade3-8c3b793737ea)
![IMG_5059](https://github.com/celogeek/go-comic-converter/assets/26210577/0293fd28-ca13-4fe4-9eba-a5372e89c49d)
![IMG_5060](https://github.com/celogeek/go-comic-converter/assets/26210577/70cd4893-5047-4b04-a4a7-01f784c056ed)
![IMG_5061](https://github.com/celogeek/go-comic-converter/assets/26210577/4684b75e-509e-4541-87d0-b73a6bf606b7)

**Comment by celogeek** [comment]
Oh, yes it's very helpful !

I spot several things.

First, KCC do not use absolute position. Which is something I would like to achieve.

My version have an image in absolute position, which is floating outside the body. I try with absolute on the body and relative for the image but the end result is not good. It works good on kindle but may be kind of broken on some readers.

The second point is the view port.
My view port keep a ratio of 1.6 like you ask for, but the one from KCC is around 1.47 which is the ratio provided by the image.
My goal for the aspect ratio is to have consistant ratio for every page, and then put the image align inside this view port.

The third think I notice, is that KCC is centring the image, so you may have big margin on landscape mode between the 2 pages.
I have opt for aligning to the right the left image, and to the left the right image, so they looks close on landscape.
It's very visible for double page, which looks like they almost glue together.

I will create a branch, and try to rework on positioning the content without absolute position.

If I end up with something satisfying on kindle, then I would guess it will be ok on kobo, but you will have to tell me.
If alignment left/right doesn't workout well on kobo, I can add profile management which will center instead for kobo device (or non kindle device).

working on it

**Comment by celogeek** [comment]
So, I've rewrite the style and try to make it more compatible.
Can you try the branch: [23-epub-problems-on-koko-device](https://github.com/celogeek/go-comic-converter/tree/23-epub-problems-on-koko-device)
Let me know how it behave.

I have a very strange bug, sometimes for no reason, even with center align, the right go to left and the left to right, in landscape.
I will have to figure it out. I don't understand.
I've got the same issue on this branch or the prod version.
It's only on kindle device.

**Comment by yoanhg421** [comment]
Ok.  I’ll let you know. Thank you.

**Comment by yoanhg421** [comment]
Everything is still the same, except the images are now smaller and the double pages are lower in the screen but still not centered. 

I can send you pictures in the morning, about to go to bed.

**Comment by yoanhg421** [comment]
With the style changes, the book displays normally on KOBO.
There is still the issue with the toc not showing up. and it's because its missing the ncx file. 

Here is the KCC version

toc.ncx:

```
<?xml version="1.0" encoding="UTF-8"?>
<ncx version="2005-1" xml:lang="en-US" xmlns="http://www.daisy.org/z3986/2005/ncx/">
<head>
<meta name="dtb:uid" content="urn:uuid:abf90247-b8a6-4e5a-86f7-0a7cad9c018e"/>
<meta name="dtb:depth" content="1"/>
<meta name="dtb:totalPageCount" content="0"/>
<meta name="dtb:maxPageNumber" content="0"/>
<meta name="generated" content="true"/>
</head>
<docTitle><text>Kill la Kill</text></docTitle>
<navMap>
<navPoint id="Text_episode-0001"><navLabel><text>Episode 1</text></navLabel><content src="Text/episode-0001/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0002"><navLabel><text>Episode 2</text></navLabel><content src="Text/episode-0002/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0003"><navLabel><text>Episode 3</text></navLabel><content src="Text/episode-0003/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0004"><navLabel><text>Episode 4</text></navLabel><content src="Text/episode-0004/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0005"><navLabel><text>Episode 5</text></navLabel><content src="Text/episode-0005/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0006"><navLabel><text>Episode 6</text></navLabel><content src="Text/episode-0006/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0007"><navLabel><text>Episode 7</text></navLabel><content src="Text/episode-0007/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0008"><navLabel><text>Episode 8</text></navLabel><content src="Text/episode-0008/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0009"><navLabel><text>Episode 9</text></navLabel><content src="Text/episode-0009/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0010"><navLabel><text>Episode 10</text></navLabel><content src="Text/episode-0010/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0011"><navLabel><text>Episode 11</text></navLabel><content src="Text/episode-0011/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0012"><navLabel><text>Episode 12</text></navLabel><content src="Text/episode-0012/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0013"><navLabel><text>Episode 13</text></navLabel><content src="Text/episode-0013/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0014"><navLabel><text>Episode 14</text></navLabel><content src="Text/episode-0014/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0015"><navLabel><text>Episode 15</text></navLabel><content src="Text/episode-0015/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0016"><navLabel><text>Episode 16</text></navLabel><content src="Text/episode-0016/kcc-0000-kcc.xhtml"/></navPoint>
<navPoint id="Text_episode-0017"><navLabel><text>Episode 17</text></navLabel><content src="Text/episode-0017/kcc-0000-kcc.xhtml"/></navPoint>
</navMap>
</ncx>
```

And when `-hascover=1` covers doesn't show up and there is a blank page after the first page. 
`-hascover=0` has to be set so the cover shows up properly in the KOBO, but this also makes the first Image the Cover.

**Comment by yoanhg421** [comment]
![IMG_5065](https://github.com/celogeek/go-comic-converter/assets/26210577/cb4fa97e-9f7c-4db7-89a7-f20e5c73dd56)
![IMG_5066](https://github.com/celogeek/go-comic-converter/assets/26210577/e12650c9-100f-4e14-8ad0-a7b0b7fcfb63)
![IMG_5067](https://github.com/celogeek/go-comic-converter/assets/26210577/a545dd4c-efa1-4a03-bf0b-8815044cee7d)

**Comment by yoanhg421** [comment]
The changes work great on all devices. except I do see the gap you were talking about when on landscape.

![IMG_5068](https://github.com/celogeek/go-comic-converter/assets/26210577/bcb14342-8fbe-4359-a9a5-d601a7673dcc)
![IMG_5069](https://github.com/celogeek/go-comic-converter/assets/26210577/588d4e9f-3fe4-499b-a22e-3cfbf4daf5cd)

**Comment by yoanhg421** [comment]
Instead on passing the image width and height to the image style. can you try passing the viewport width and height. like KCC does that might fix it. I don't know enough GO to do it and test for the gap.

**Comment by celogeek** [comment]
The image is align to center. And even they take the full width of each viewport, it seems to have space between each split.
When I use absolute position with align left or right, it solve this issue, as it seems the image is placed outside the body.
But this mode make rendering on some device very bad. Only center seems ok.

And for portrait, it looks on the Kindle that the align left/right is ignore and the image is placed on the middle.

**Comment by celogeek** [comment]
The NCX is for old epub version. As the kindle support the last one, I removed it at some point.
I will add it back for compatibility with older devices.

**Comment by yoanhg421** [comment]
Best solution is to install KoReader on Kobo device and transfer a CBZ of the Manga.
