### ISSUE TITLE
split double page with crop enable

### ISSUE THREAD

**Issue by ssbroad** [celogeek/go-comic-converter#28]
The crop logic is problematic when the program is dealing with double pages. 

At present, the program will first trim the whole edge, and then divide the pages. I think this is the wrong thing to do.

As shown in the following:

![1](https://github.com/celogeek/go-comic-converter/assets/11014064/61ec8160-9a3f-433d-9580-a50d73b84c6c)
![2](https://github.com/celogeek/go-comic-converter/assets/11014064/e1fe74b6-8953-44cd-b110-902b819bf59b)
![3](https://github.com/celogeek/go-comic-converter/assets/11014064/1ea3f8f6-d7aa-4890-be9f-9d130b91462d)
![4](https://github.com/celogeek/go-comic-converter/assets/11014064/093df9c2-73d6-4207-a592-93ea1acfbe96)

We'll get two completely wrong pictures!!!

The correct processing order should be split page first, and then crop each segmented page.

![5](https://github.com/celogeek/go-comic-converter/assets/11014064/25f38c08-9e25-41f0-ad05-87cb5ec4c9c9)

**Comment by celogeek** [comment]
Good catch. Will try to fix that. Can you provide the original image ?

**Comment by ssbroad** [comment]
> Good catch. Will try to fix that. Can you provide the original image ?

https://imgur.com/y5MKauw

**Comment by celogeek** [comment]
When I check the size of the original image, I can tell if the X > Y that this is a double page.
Usually we have blank if needed for title or stuff like that.

If I crop first, then check the new size, and see X < Y, like in your case then it's not a double page anymore on the opposite of your original image. So I can skip the splitting in that case.

But let's take this one:

---
![One Piece T001 - 002](https://github.com/celogeek/go-comic-converter/assets/65178/5c606708-a283-4d39-85ce-5c570ff093a2)
---

After cropping the blank page, X > Y, so the title is split in two. If I check the original image, it's not a double page.

So your logic is also not working in all situation.

**Comment by celogeek** [comment]
Here the result:
---
![img_1_p0](https://github.com/celogeek/go-comic-converter/assets/65178/d975da2b-e84f-49e0-bf21-c3d2ce85ce7a)
---
![img_1_p2](https://github.com/celogeek/go-comic-converter/assets/65178/3f9217f6-6620-4ad4-9389-894387191b2f)
---
![img_1_p1](https://github.com/celogeek/go-comic-converter/assets/65178/501ec1c3-dd56-41c6-9958-4cf4474aeb29)
---

**Comment by celogeek** [comment]
I would say may be a double page is when the original and the cropped version are detected as double page. Otherwise we set it as simple page.

In your case the original is a double page, but not the cropped version, so we should not split it.
In my case the original is not a double page, but the cropped version seems to be one, so we should not split it.

If we have a truly double page, then original and cropped should be detected as a double page.

**Comment by ssbroad** [comment]
let's view this pic:
https://imgur.com/YJmsc7m

we will get page 1 is:
https://imgur.com/QNV17tP

But it's actually possible to cut edges more accurately:
https://imgur.com/Dlc2bYv

This result is what I call the order problem. If you trim the edges before split double page, the program will be affected by the image on the left(or right), so that the edges cannot be accurately trimmed.

**Comment by celogeek** [comment]
Oh ok I see it now.

Actually on the splitted image, I apply the same filter as the original, and I add a cut in half at the end.
I should cut fiest, then apply each filter.

I will see if that may lead to issue the other filters.

**Comment by celogeek** [comment]
For the flow, may be this one:

- crop original
- check if the original and cropped version are still a double page
- split double page from the cropped version
- reapply a crop on each side to cut more

Alternatively
- check if the original before any filter is a double page
- split double page from the original untouch
- apply crop on each side (and other filter)

**Comment by ssbroad** [comment]
Sorry, I don't know the Go language, so does the second method take up less memory? 
The program will have memory problems when dealing with some ultra-high quality manga.

**Comment by celogeek** [comment]
Memory is not really an issue, as soon as I have process images I store it into a local file and free the memory.

I try to split then apply all the filter. The issue is the Crop filter is a bit special, it need to read the image and then it tell the library I use to crop where to crop.
So I need to tell to take a look with limits.

It's not trivial.

**Comment by celogeek** [comment]
I've made a patch in that branch: 28-split-double-page-with-crop-enable
You can clone it, checkout the branch, then test it.
```
git clone https://github.com/celogeek/go-comic-converter.git
cd go-comic-converter
git checkout 28-split-double-page-with-crop-enable
go run . [PARAMS HERE]
```

**Comment by celogeek** [comment]
It seems ok for my test, I will keep testing it a bit then merge and release.
Let me know if it doesn't work for some case.

**Comment by ssbroad** [comment]
perfect! https://imgur.com/jt0vFma
Thank you for your work.
