### ISSUE TITLE
Cannot turn off boolean options.

### ISSUE THREAD

**Issue by odeinjul** [celogeek/go-comic-converter#31]
Hi! Thanks for this tool!

**What happened**
I'm trying to use this tool to convert some manga, but the output epub is grayscaled while I want the manga to stay colorful. So after read the help, I found the ```-grayscale``` option, which is true by default. 

Then I noticed **there isn't any way to turn off this option** except directly modify the default config (```.go-comic-converter.yaml```), because this option doesn't support the format like ```-grayscale true/false```. It only supports ```-grayscale``` to turn on ```grayscale```, but this option is already true by default.

**What should happen**
IMO boolean options with command like the ```-grayscale``` above should have a default value as ```false``` to make sense, or we can change the format of these commands to ```-grayscale bool```.
---
If there's anything wrong with my description, please point out as I only learned go for weeks and also not familiar with this tool.

**Comment by celogeek** [comment]
I've got some example in the doc to turn off a option.

```
-grayscale=0
```

the module I use to parse the flag are common with golang tools.
I have a series of settings as a sane default, when you don't have any config, as a kick start.
So to turn off those option you need to use this syntax above (=0)

Let me know if it doesn't work.

**Comment by odeinjul** [comment]
Thanks for your reply! Use a command like ```-grayscale=0``` or ```-grayscale=false``` works for me.
