### ISSUE TITLE
Add limts to crop page. 

### ISSUE THREAD

**Issue by ssbroad** [celogeek/go-comic-converter#32]
After making and reading a lot of comics using converter, I found that some comics like to add a simple illustration at the end of each chapter, like this: 

![upi-132](https://github.com/celogeek/go-comic-converter/assets/11014064/54e0cf50-1da7-47e0-8172-dd045f7f9a55)

The cropped picture will be forced to enlarge to match the device screen. 

However, because of the resolution, it is very blurred. 

![upi-1322](https://github.com/celogeek/go-comic-converter/assets/11014064/f25a3066-02ff-4a9b-af30-7b46306b896c)

Applying cropping to these special pictures would be a disaster. 

Auto crop should set a limit, for example, no more than 30% of height or width.

**Comment by celogeek** [comment]
Hi,
I have a branch with a crop-limit option.
by default it's 0, meaning like now, no limit.
The option is a number of maximum pixel allow to be cropped on all side.

To try:
```
go install github.com/celogeek/go-comic-converter/v2@32-add-limts-to-crop-page
go-comic-converter -crop-limit 50 # your settings there
```

I wonder if this limit should be a wait to cancel the crop.
like crop-only-if-below 50
if we see we cut more, then we don't cut anything.

let me know about it

**Comment by ssbroad** [comment]
I think it's good to manually enter 10% of the width of the picture. 
By the way, "-keepdoublepageifsplitted" in README seems to be out of date and is now called "-keepdoublepageifsplit".

**Comment by ssbroad** [comment]
Thank you for your work. After some tests, I have some new suggestions. 
I noticed that the current pixel limit for cropping is applied after image processing.

Here is a new method: 
If we prejudge the pixels that are normally cropped, and then compare them with the limits of clipping. 
If it is greater than the limit value, no clipping is applied.

For example: 
After detection on the left side of the picture, 200 pixels should be clipped, which is greater than the 50 pixel limit we set, so we will not cut any pixels on the left side of the picture, that is, cropping is prohibited.
It's the same on the right. 

~~I think this method is more in line with our expected effect on the crop limit parameters, after all, the purpose of the limit is to avoid the application of cropping in these special images.~~

Well, after some consideration, I think the current way of implementation may also be good.

**Comment by celogeek** [comment]
It may be more interesting to use a percentage instead of a hard pixel limit. This way it will be proportional to the image we process.
May be I can add another option to cancel the crop if the limit is reached.
```
-crop-limit 10 # maximum 10% of width and height
-crop-skip-if-limit-reached
```

**Comment by celogeek** [comment]
I update the crop-limit to a percentage. try 5% for example.

let me know:
```
go install github.com/celogeek/go-comic-converter/v2@c500755a4e77f365efca8a957ab96312854b3884
```

**Comment by celogeek** [comment]
I will add an option to cancel cropping. this way we can have a choice.

**Comment by celogeek** [comment]
I add an option for skipping crop if limit is reached

```
go install github.com/celogeek/go-comic-converter/v2@f4501753c54792fd76ce88437537f6a0c11ca025

-crop-limit 10
-crop-skip-if-limit-reached
```

To turn off
```
-crop-skip-if-limit-reached=false
```

**Comment by celogeek** [comment]
I've release this. you can install the v2.7.0
Let me know if you find some bugs.

**Comment by ssbroad** [comment]
> I've release this. you can install the v2.7.0 Let me know if you find some bugs.

great performance!

By the way, the program doesn't seem to be able to handle pictures in tiff format, but it supports webp well.

**Comment by celogeek** [comment]
I can easily add tiff support.
let's close this issues and create a new one.

**Comment by celogeek** [comment]
I added the tiff support. pickup the last release
