### ISSUE TITLE
Getting blank images every other page

### ISSUE THREAD

**Issue by luislve17** [celogeek/go-comic-converter#42]
Hi,

I just attempted to convert a single `.cbz`. Trying multiple setups I always get the same issue once i load it to my e-reader.
Am doing:
```
go-comic-converter -hascover -manga -auto -profile KoL -limitmb 200 -aspect-ratio -1 -crop-ratio-bottom 0 -strip -input 'Pluto - Urasawa x Tezuka v01 (2009) (
Digital) (LuCaZ).cbz'
```
But the issue is persistent using any kind of combinations of the config flags, and also with other `.cbz` I've tried
Opening on my PC's epub reader shows a couple of blank pages at the beginning but nothing else, and (important to notice) when reading it on my e-redear, the blank pages correspond to the same previous page. For example, page number 3 shows the content, and going to next page it still shows to be page number 3, now blank. 

Reading around it seems to be a resolution /  image size, but not sure how to run the converter without getting these blank pages.

I use a Kobo Libra 2

Thanks in advance

**Comment by luislve17** [comment]
Hopefully this shows better what i mean:

https://github.com/user-attachments/assets/6dff5143-9a71-478f-bca3-27d8cade6ad6

**Comment by celogeek** [comment]
Try with -noblankimage and may be -portrait-only too. 

Just before running you command send the -show result ( add it at the end of your command ). So I can see every option sets.

**Comment by luislve17** [comment]
Let me see, using:
```
go-comic-converter -manga -profile KoL -aspect-ratio -1 -crop-ratio-bottom 0 -noblankimage -portrait-only -input 'Pluto - Urasawa x Tezuka v01 (2009) (Digital) (LuCaZ).cbz'
 -show
Go Comic Converter

Options: 
    Profile                         : KoL - Kobo Libra H2O/Kobo Libra 2 - 1264x1680
    Format                          : jpeg
    Quality                         : 85
    Grayscale                       : true
    Grayscale mode                  : normal
    Crop                            : true
    Crop ratio                      : 1 Left - 1 Up - 1 Right - 0 Bottom - Limit 0% - Skip false
    Auto contrast                   : false
    Auto rotate                     : false
    Auto split double page          : false
    No blank image                  : true
    Manga                           : true
    Has cover                       : true
    Strip first directory from toc  : false
    Sort path mode                  : path=alphanumeric, file=alpha
    Foreground color                : #000
    Background color                : #FFF
    Resize                          : true
    Aspect ratio                    : 1:1.33 (device)
    Portrait only                   : true
    Title page                      : always
```

I still have the same issue
Edit: I tried rotating my view in the kobo, and it now goes well without the blank page, but has a blank gap on the right. I also had to zoom out in order to see the pages, since it was all blank when i first put it on landscape view horizontally.

https://github.com/user-attachments/assets/6e0d0702-9af1-45f0-b373-f9222a0131c2

**Comment by celogeek** [comment]
Add -autorotate, and use the portrait mode on your device. 
It should be rotate properly but in portrait mode.

**Comment by luislve17** [comment]
Adding it:
```
go-comic-converter -manga -profile KoL -aspect-ratio -1 -crop-ratio-bottom 0 -noblankimage -portrait-only -autorotate -input 'Pluto - Urasawa x Tezuka v01 (20
09) (Digital) (LuCaZ).cbz'
```
Correctly accepts it (the option)
```
Options:
    Input                           : Pluto - Urasawa x Tezuka v01 (2009) (Digital) (LuCaZ).cbz
    Output                          : Pluto - Urasawa x Tezuka v01 (2009) (Digital) (LuCaZ).epub
    Author                          : GO Comic Converter
    Title                           : Pluto - Urasawa x Tezuka v01 (2009) (Digital) (LuCaZ)
    Workers                         : 8
    Profile                         : KoL - Kobo Libra H2O/Kobo Libra 2 - 1264x1680
    Format                          : jpeg
    Quality                         : 85
    Grayscale                       : true
    Grayscale mode                  : normal
    Crop                            : true
    Crop ratio                      : 1 Left - 1 Up - 1 Right - 0 Bottom - Limit 0% - Skip false
    Auto contrast                   : false
    Auto rotate                     : true
    Auto split double page          : false
    No blank image                  : true
    Manga                           : true
    Has cover                       : true
    Strip first directory from toc  : false
    Sort path mode                  : path=alphanumeric, file=alpha
    Foreground color                : #000
    Background color                : #FFF
    Resize                          : true
    Aspect ratio                    : 1:1.33 (device)
    Portrait only                   : true
    Title page                      : always

[1/2] Processing      100% [============================================================] (202/202)         
[2/2] Writing Part    100% [============================================================] (1/1)             
                                                                                                       
Completed in 22.801s, Memory usage 805 Mb
```
But issue persists

**Comment by celogeek** [comment]
Can you share your source. I will give it a try. 

Also which version do you used ?

**Comment by luislve17** [comment]
Sure, I downloaded it from [here](https://nyaa.si/view/1721303), volume 1
Checking the version
```
go-comic-converter -version
go-comic-converter
  Path             : github.com/celogeek/go-comic-converter/v2
  Sum              : h1:ww3ssN0AIGezxc/63n5y3aoMlzOhCQeUto9TrVI39O8=
  Version          : v2.7.2
  Available Version: v2.7.2

To install the latest version:
$ go install github.com/celogeek/go-comic-converter/v2@v2.7.2
```

**Comment by celogeek** [comment]
Just in case, can you try the master branch ?

**Comment by celogeek** [comment]
I test it locally, opening with Apple Book for instance, I don't see any spaces.
I've check the content of the epub (unzip it), I don't see spaces included.
Can you try with another aspect ration, like : -aspect-ratio 1.6

**Comment by luislve17** [comment]
Sorry, for the late response.
I tried it from the main branch, and later with the fixed aspect ratio as you suggested. I keep getting this issue.
Anyhow, i decided to use KCC's CLI tool for my project. Not sure how it makes a difference but with KCC's i didn't have any issues.
Sorry for the inconvenience, you may close this issue now

**Comment by celogeek** [comment]
Unfortunately I don't have this device. So it's complicated to debug.
It's not the first time I've got issues with device different than a kindle.
To clarify until I can really ensure it works on other device, I will remove the profiles.

**Comment by luislve17** [comment]
No worries. Thank you a lot for your time. You have a nice project in your hands 🙂
