### ISSUE TITLE
Specify file name when there is an unknown/corrupt image format

### ISSUE THREAD

**Issue by darodi** [celogeek/go-comic-converter#5]
I tried to convert a big directory with sub directories.
One of the images was corrupt.
It would be great to have the file name of the problematic image in the error message

![image](https://user-images.githubusercontent.com/4682830/230600514-01843ced-acc2-410a-8c8a-323959a4d1af.png)

**Comment by celogeek** [comment]
Wow ! I hope you have enough memory.
Indeed, yes, this happen in a multi thread env. I will improve the error message (may be close the processing).

Also may be useful to add an "ignore-errors" options, to keep going but just display warnings.

**Comment by celogeek** [comment]
done for improve part of the error message
checkout last version:

```
go install github.com/celogeek/go-comic-converter/v2@v2.0.3
```

**Comment by darodi** [comment]
Thanks! 
The "corrupt" file was in webp format.
I've created a new PR 
- #6
